<a href="https://colab.research.google.com/github/ag999git/001-Python-book-2026/blob/main/colab-nb/03_Chapter3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Note:- In Python, the sign of the remainder is the same as the sign of the denominator (which differs from languages like C, where it is the same as the sign of the numerator). This is clear from following:-

In [1]:
# In Python, sign of remainder (%) always follows sign of denominator

# Example 1 — Negative numerator, positive denominator
print(-7 % 3)  # Output: 2
# Explanation: -7 divided by 3 is -3 with remainder 2, since -3 * 3 + 2 = -7

# Example 2 — Positive numerator, negative denominator
print(7 % -3)  # Output: -2
# Explanation: 7 divided by -3 is -3 with remainder -2, since -3 * -3 + -2 = 7

# Example 3 — Negative numerator, negative denominator
print(-7 % -3)  # Output: -1
# Explanation: -7 divided by -3 is 2 with remainder -1, since 2 * -3 + -1 = -7


2
-2
-1


Using operatot `+` that is addition and operator `*` that is multiplication on various data types

In [2]:
# 1. Using + with numbers → Performs addition
print(5 + 3)  # Output: 8
# Explanation: The + operator adds two numeric values together.

# 2. Using + with strings → Performs concatenation
print("Hello, " + "world!")  # Output: Hello, world!
# Explanation: The + operator concatenates two strings together.

# 3. Using + with lists → Merges two lists
print([1, 2] + [3, 4])  # Output: [1, 2, 3, 4]
# Explanation: The + operator merges two lists into one.

# 4. Using * with numbers → Performs multiplication
print(4 * 2)  # Output: 8
# Explanation: The * operator multiplies two numeric values together.

# 5. Using * with strings → Repeats the string
print("abc " * 3)  # Output: abc abc abc
# Explanation: The * operator repeats the string a specified number of times.

# 6. Using * with lists → Repeats the list
print([1, 2, 3] * 3)  # Output: [1, 2, 3, 1, 2, 3, 1, 2, 3]
# Explanation: The * operator repeats the list a specified number of times.

# 7. Using * with tuples → Repeats the tuple
print((4, 5) * 2)  # Output: (4, 5, 4, 5)
# Explanation: The * operator repeats the tuple a specified number of times.


8
Hello, world!
[1, 2, 3, 4]
8
abc abc abc 
[1, 2, 3, 1, 2, 3, 1, 2, 3]
(4, 5, 4, 5)


Comparison operators in Python:-There are 6 comparison operations in Python. Comparison operators are used to compare values.

In [ ]:
# 1. <  (Less than)
print(3 < 5)   # True  -> 3 is strictly less than 5
# Explanation: The < operator checks if the value on the left is less than the value on the right.

# 2. <= (Less than or equal to)
print(5 <= 5)   # True  -> 5 is equal to 5, condition satisfied
# Explanation: The <= operator checks if the value on the left is less than or equal to the value on the right.

# 3. >  (Greater than)
print(10 > 2)   # True  -> 10 is strictly greater than 2
# Explanation: The > operator checks if the value on the left is greater than the value on the right.

# 4. >= (Greater than or equal to)
print(7 >= 9)   # False -> 7 is NOT greater than or equal to 9
# Explanation: The >= operator checks if the value on the left is greater than or equal to the value on the right.

# 5. == (Equal to)
print(4 == 4)   # True  -> both values are equal
# Explanation: The == operator checks if the value on the left is equal to the value on the right.

# 6. != (Not equal to)
print(8 != 3)   # True  -> 8 and 3 are different values
# Explanation: The != operator checks if the value on the left is not equal to the value on the right.


Interning (Advance concept)

Interning is a memory-optimization technique where Python reuses certain immutable objects instead of creating new ones every time

In [4]:
# Example 1: Small Integer Interning
a = 256
b = 256
print(a is b)  # True -> small integers are interned
print(a == b)  # True -> values are equal

# Example 2: Large integers (not interned by default)
num1 = 10000
num2 = 10000
print(num1 is num2)  # False in some implementations
print(num1 == num2)  # True -> values are equal
# Explanation: 'is' checks for object identity, while '==' checks for value equality.

# Example 3: Interning does NOT affect ==, because the values
# are compared, not the object locations.
x = 1000000
y = 1000000
print(x is y)  # False in some implementations
print(x == y)  # True -> values are equal

# Example 4: String Interning
str1 = "hello"
str2 = "hello"
print(str1 is str2)  # True -> due to string interning
print(str1 == str2)  # True -> values are equal

# Example 5: Large strings (not interned by default)
large_str1 = "a" * 1000
large_str2 = "a" * 1000
print(large_str1 is large_str2)  # False in some implementations
print(large_str1 == large_str2)  # True -> values are equal

# Example 6: Lists are not interned
list1 = [1, 2, 3]
list2 = [1, 2, 3]
print(list1 is list2)  # False -> different objects in memory
print(list1 == list2)  # True -> values are equal


True
True
False
True
False
True
True
True
True
True
False
True


The following script shows how bitwise operators work in Python

In [ ]:
# Example 1: Bitwise AND Operator(&) compares each
# bit of two integers. # 6 → binary: 00000110
# 5 → binary: 00000101. AND means 1 only if both bits are 1.
# So 6 & 5 is → 00000100 (in binary) → 4 (In decimal)
print(6 & 5)  # Output: 4

# Example 2: Bitwise OR Operator(|) compares each bit of two
# integers. 6 → binary: 00000110. 5 → binary: 00000101, OR
# OR (|) means 1 if at least one of the two bits is 1. So 6 | 5 is→ 00000111 → 7
print(6 | 5)  # Output: 7

# Example 3: Bitwise XOR Operator (^) compares each bit of
# two integers 6 → binary: 00000110 5 → binary: 00000101.
# XOR means 1 only if the bits are different.
# So 6 ^ 5 → 00000011 → 3 (Bitwise XOR)
print(6 ^ 5)  # Output: 3

# Example 4: Bitwise NOT Operator (~) inverts all the bits of
# an integer. 6 in binary:-> 00000110. In two's complement
# representation, this equals -7. So ~6 → 11111001 → -7
print(~6)  # Output: -7

# Example 5: Left Shift Operator (<<) shifts the bits of an
# integer to the left by a specified number of positions.
# 6 in binary: -> 00000110. So 6 << 1 → 00001100 → 12
print(6 << 1)  # Output: 12

# Example 6: Right Shift Operator (>>) shifts the bits of an
# integer to the right by a specified number of positions.
# 6 in binary: -> 00000110. So 6 >> 1 → 00000011 → 3
print(6 >> 1)  # Output: 3


The following script shows use of membership and identity operators:-

In [ ]:
# Example 1: Identity vs Equality
a = b = [1, 2, 3]      # a and b refer to the SAME list object
c = [1, 2, 3]          # c has the same value but is a DIFFERENT object
print(a is b)  # True -> a and b point to the same object
print(a is c)  # False -> a and c are different objects
print(a == c)  # True -> a and c have the same value

# Example 2: Membership Operators
print('a' in 'abcd')   # True -> 'a' is found in the string 'abcd'
print(5 not in [1, 2, 3])  # True -> 5 is not in the list [1, 2, 3]

# Example 3: Dictionary Membership tests keys only
my_dict = {'x': 10, 'y': 20}
print('x' in my_dict)  # True -> 'x' is a key in the dictionary
print(10 in my_dict)   # False -> 10 is a value, not a key


Matrix Multiplication Operator (@)
Operator (@) was introduced in Python 3.5 and later. It is useful for matrix and vector multiplications especially in NumPy. Study Matrix Multiplication Operator (`@`)

The following script explains how Matrix Multiplication Operator (`@`) works

In [1]:
# Note: The @ operator is only available in Python 3.5 and later versions.
# For matrix operations, it's often more efficient to use NumPy arrays instead of nested lists.
# In this example, we used NumPy to create matrices and perform multiplication, which is optimized for performance.
# The @ operator is a convenient way to express matrix multiplication in a clear and concise manner.
# Always ensure that the dimensions of the matrices or vectors are compatible for multiplication when using the @ operator.
# For matrix multiplication, the number of columns in the first matrix must equal the number of rows in the second matrix.
# For matrix-vector multiplication, the number of columns in the matrix must equal the number of elements in the vector.


# This script demonstrates the use of the @ operator for matrix multiplication
# in Python. The @ operator is used to perform matrix multiplication between two
# matrices (2D lists) or between a matrix and a vector (1D list).
# =============================================================
import numpy as np
# Example 1: Matrix-Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A @ B  # Matrix multiplication of A and B
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Result of A @ B:\n", C)  # Should output the product of A and B
# Example 2: Matrix-Vector Multiplication
M = np.array([[1, 2], [3, 4]])
v = np.array([5, 6])
result = M @ v  # Matrix multiplication of M and v
print("Matrix M:\n", M)
print("Vector v:\n", v)
print("Result of M @ v:\n", result)  # Should output the product of M and v

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Result of A @ B:
 [[19 22]
 [43 50]]
Matrix M:
 [[1 2]
 [3 4]]
Vector v:
 [5 6]
Result of M @ v:
 [17 39]


#### 2. There are also set operators in Python. Python supports the following set operators:- (1) `|`   union (2) `&`   intersection (3) `-`   difference (4) `^`   symmetric difference. Study these set operators in Python


In [ ]:
"""
Set Operators
Sets support:

|   union
&   intersection
-   difference
^   symmetric difference

"""

# Example 1: Union
set_a = {1, 2, 3}
set_b = {3, 4, 5}
union_set = set_a | set_b
print("Union:", union_set)  # Output: {1, 2, 3, 4, 5}

# Example 2: Intersection
intersection_set = set_a & set_b
print("Intersection:", intersection_set)  # Output: {3}

# Example 3: Difference
difference_set = set_a - set_b
print("Difference (A - B):", difference_set)  # Output: {1, 2}

# Example 4: Symmetric Difference
symmetric_diff_set = set_a ^ set_b
print("Symmetric Difference:", symmetric_diff_set)  # Output: {1, 2, 4, 5}
