
## 40 script-based exercises 
________________________________________

1. Create a 1D NumPy array containing the numbers from 10 to 49. Then, reverse this array using slicing.

In [1]:
import numpy as np

# Create the array using arange
arr = np.arange(10, 50)

# Reverse the array using the [start:stop:step] slicing syntax with step -1
reversed_arr = arr[::-1]

print("Original:", arr)
print("Reversed:", reversed_arr)


Original: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Reversed: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


2. Create a 3x3 matrix with values ranging from 0 to 8 using `np.reshape`.

In [2]:
import numpy as np

# Create 9 elements and reshape into a 3x3 grid
# Requirement: total elements must match the product of dimensions (3*3=9)
matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Initialize a `5x5` identity matrix and change all the diagonal elements to 5.

In [3]:
import numpy as np

# np.eye creates a square matrix with 1s on the diagonal
identity = np.eye(5)

# Multiply the entire matrix by 5 (Broadcasting a scalar)
# Since only the diagonal has 1s, only they become 5
five_diag = identity * 5

print(five_diag)


[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


4. Generate a `10x10` array with random values. Find the minimum and maximum values and their memory addresses.

In [4]:
import numpy as np

# Create random floats in [0, 1)
data = np.random.rand(10, 10)

# Use built-in aggregate functions
min_val = data.min()
max_val = data.max()

print(f"Min: {min_val}, Max: {max_val}")
# The data pointer shows the memory start location
print(f"Memory Address: {data.ctypes.data}")


Min: 0.008619616524831564, Max: 0.9971118358504557
Memory Address: 2336178146528


5. Create a `2D` array with 1 on the border and 0 inside.

In [5]:
import numpy as np

# Initialize with ones
x = np.ones((5, 5))

# Use slicing to target the 'interior' (everything except first/last row and col)
# Assign 0 to that sub-view
x[1:-1, 1:-1] = 0

print(x)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Create an `8x8` matrix and fill it with a checkerboard pattern (0s and 1s) using slicing.

In [6]:
import numpy as np

check = np.zeros((8, 8), dtype=int)

# Every second row starting from index 1, every second column starting from index 0
check[1::2, ::2] = 1

# Every second row starting from index 0, every second column starting from index 1
check[::2, 1::2] = 1

print(check)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


7. Convert an array of weights `[70.5, 80.2, 65.0]` from kilograms to pounds (1kg = 2.2lb) using vectorization.

In [7]:
import numpy as np

weights_kg = np.array([70.5, 80.2, 65.0])

# Vectorization allows us to multiply the whole array by a scalar without a for-loop
weights_lb = weights_kg * 2.2

print(f"Weights in lbs: {weights_lb}")


Weights in lbs: [155.1  176.44 143.  ]


8. Demonstrate the "View vs Copy" behavior by slicing an array and modifying the slice. Verify the original array.

In [8]:
import numpy as np

original = np.array([1, 2, 3, 4, 5])

# Slicing creates a 'view' (shared memory)
slice_view = original[0:3]
slice_view[0] = 99

print("Modified Original:", original) # Should show 99 at index 0

# To keep original safe, use .copy()
safe_copy = original[0:3].copy()
safe_copy[1] = 88

print("Original after modifying copy:", original) # Should NOT show 88


Modified Original: [99  2  3  4  5]
Original after modifying copy: [99  2  3  4  5]


9. Given a `4x4` matrix, extract the inner `2x2` sub-matrix.

In [9]:
import numpy as np

matrix = np.arange(16).reshape(4, 4)

# Slicing rows 1 to 2 (index 1:3) and columns 1 to 2 (index 1:3)
inner = matrix[1:3, 1:3]

print("Full Matrix:\n", matrix)
print("Inner Sub-matrix:\n", inner)


Full Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Inner Sub-matrix:
 [[ 5  6]
 [ 9 10]]


10. Normalize a random `5x5` matrix so that all values lie between 0 and 1.

In [10]:
import numpy as np

rand_arr = np.random.rand(5, 5) * 100

# Normalization formula: (x - min) / (max - min)
normalized = (rand_arr - rand_arr.min()) / (rand_arr.max() - rand_arr.min())

print(normalized)


[[0.85888017 0.57014505 0.72387388 0.58025987 0.03215741]
 [0.82050704 0.         1.         0.98689692 0.45736881]
 [0.82237609 0.66032999 0.16741997 0.63150061 0.08121873]
 [0.28089033 0.97370075 0.59791878 0.30958224 0.2174109 ]
 [0.43551026 0.82067132 0.36087822 0.30341363 0.22160236]]


11. Create a script to find the common values between two NumPy arrays.

In [11]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

# np.intersect1d finds unique common elements
common = np.intersect1d(arr1, arr2)

print("Common elements:", common)


Common elements: [3 4 5]


12. Generate 50 evenly spaced numbers between 0 and $2π$ and calculate their sine values.

In [12]:
import numpy as np

# linspace is preferred when the number of points is fixed
x = np.linspace(0, 2 * np.pi, 50)

# np.sin is a universal function (ufunc) that works element-wise
y = np.sin(x)

print(y)


[ 0.00000000e+00  1.27877162e-01  2.53654584e-01  3.75267005e-01
  4.90717552e-01  5.98110530e-01  6.95682551e-01  7.81831482e-01
  8.55142763e-01  9.14412623e-01  9.58667853e-01  9.87181783e-01
  9.99486216e-01  9.95379113e-01  9.74927912e-01  9.38468422e-01
  8.86599306e-01  8.20172255e-01  7.40277997e-01  6.48228395e-01
  5.45534901e-01  4.33883739e-01  3.15108218e-01  1.91158629e-01
  6.40702200e-02 -6.40702200e-02 -1.91158629e-01 -3.15108218e-01
 -4.33883739e-01 -5.45534901e-01 -6.48228395e-01 -7.40277997e-01
 -8.20172255e-01 -8.86599306e-01 -9.38468422e-01 -9.74927912e-01
 -9.95379113e-01 -9.99486216e-01 -9.87181783e-01 -9.58667853e-01
 -9.14412623e-01 -8.55142763e-01 -7.81831482e-01 -6.95682551e-01
 -5.98110530e-01 -4.90717552e-01 -3.75267005e-01 -2.53654584e-01
 -1.27877162e-01 -2.44929360e-16]


13. Create a `5x5` matrix and find the sum of each column.

In [13]:
import numpy as np

matrix = np.arange(25).reshape(5, 5)

# Axis 0 refers to the row-wise collapse (summing vertically down columns)
column_sums = matrix.sum(axis=0)

print("Matrix:\n", matrix)
print("Sums of columns:", column_sums)


Matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Sums of columns: [50 55 60 65 70]


14. Replace all values in a 1D array that are greater than 50 with the value 0 using Boolean Masking.

In [14]:
import numpy as np

arr = np.array([10, 60, 20, 80, 30])

# Step 1: Create the boolean mask
mask = arr > 50

# Step 2: Use mask to index and reassign
arr[mask] = 0

print(arr) # [10, 0, 20, 0, 30]


[10  0 20  0 30]


15. Use `np.where` to create an array that marks numbers as "Even" or "Odd" based on an input array.

In [15]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5, 6])

# np.where(condition, value_if_true, value_if_false)
labels = np.where(numbers % 2 == 0, "Even", "Odd")

print(labels)


['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']


16. Stack two 2D arrays vertically and then horizontally.

In [16]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# vstack adds rows
v = np.vstack((a, b))

# hstack adds columns
h = np.hstack((a, b))

print("Vertical:\n", v)
print("Horizontal:\n", h)


Vertical:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal:
 [[1 2 5 6]
 [3 4 7 8]]


17. Calculate the Dot Product of two `3x3` matrices.

In [17]:
import numpy as np

A = np.ones((3, 3)) * 2
B = np.eye(3)

# Use np.dot or the @ operator
dot_product = np.dot(A, B)

print(dot_product)


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


18. Create a `3x3x3` tensor and extract the second "page" (slice along Axis 0).

In [18]:
import numpy as np

tensor = np.arange(27).reshape(3, 3, 3)

# Indexing the first dimension (Axis 0)
second_page = tensor[1, :, :]

print("Full Tensor:\n", tensor)
print("Second Page:\n", second_page)


Full Tensor:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Second Page:
 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]


19. Given a 1D array of 12 elements, reshape it into a 3D array of shape `(2, 2, 3)`.

In [19]:
import numpy as np

data = np.arange(12)

# Ensure product 2*2*3 = 12
reshaped = data.reshape(2, 2, 3)

print(reshaped)


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


20. Find the indices of non-zero elements in the array `[1, 2, 0, 0, 4, 0]`.

In [20]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])

# np.nonzero returns a tuple of arrays (one for each dimension)
indices = np.nonzero(arr)

print(indices)


(array([0, 1, 4], dtype=int64),)


21. Generate a `5x5` identity matrix and add a scalar 10 to it using broadcasting.

In [21]:
import numpy as np

eye_mat = np.eye(5)

# 10 is broadcasted to every element of the 5x5 matrix
result = eye_mat + 10

print(result)


[[11. 10. 10. 10. 10.]
 [10. 11. 10. 10. 10.]
 [10. 10. 11. 10. 10.]
 [10. 10. 10. 11. 10.]
 [10. 10. 10. 10. 11.]]


22. Multiply a `3x3` matrix by a 1D row vector of length 3 using broadcasting.

In [22]:
import numpy as np

matrix = np.ones((3, 3))
vector = np.array([1, 2, 3])

# Vector is stretched vertically to match the 3 rows of the matrix
result = matrix * vector

print(result)


[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


23. Calculate the mean, median, and standard deviation of a dataset of 100 random numbers.

In [23]:
import numpy as np

data = np.random.randn(100)

# Statistical aggregations
mean_val = np.mean(data)
median_val = np.median(data)
std_dev = np.std(data)

print(f"Mean: {mean_val}, Median: {median_val}, Std: {std_dev}")


Mean: 0.06604705456879681, Median: 0.14191898345318069, Std: 0.9990749078797976


24. Solve the system of linear equations: $3x + y = 9$ and $x + 2y = 8$ using `np.linalg.solve`.

In [24]:
import numpy as np

# Coefficients matrix A
A = np.array([[3, 1], [1, 2]])

# Ordinate/Constants vector B
B = np.array([9, 8])

# Solve for [x, y]
solutions = np.linalg.solve(A, B)

print(f"x = {solutions[0]}, y = {solutions[1]}")


x = 2.0, y = 3.0


25. Compute the Eigenvalues and Eigenvectors of a `2x2` square matrix.

In [25]:
import numpy as np

mat = np.array([[1, 2], [2, 1]])

# linalg.eig returns two values: eigenvalues and the eigenvector matrix
eigenvalues, eigenvectors = np.linalg.eig(mat)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [ 3. -1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


26. Perform a Singular Value Decomposition (SVD) on a `3x2` matrix.

In [26]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])

# svd returns U, Sigma (as 1D), and VT (Transpose of V)
U, S, VT = np.linalg.svd(A)

print("U:\n", U)
print("Singular Values (Sigma):", S)
print("V Transpose:\n", VT)


U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Singular Values (Sigma): [9.52551809 0.51430058]
V Transpose:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


27. Create a coordinate grid for the range $x=-1$ to $1$ and $y=-1$ to $1$ using `np.meshgrid`.

In [27]:
import numpy as np

x = np.linspace(-1, 1, 5)
y = np.linspace(-1, 1, 5)

# Meshgrid creates two 2D arrays representing all (x,y) pairs
X, Y = np.meshgrid(x, y)

print("X Grid:\n", X)
print("Y Grid:\n", Y)


X Grid:
 [[-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]]
Y Grid:
 [[-1.  -1.  -1.  -1.  -1. ]
 [-0.5 -0.5 -0.5 -0.5 -0.5]
 [ 0.   0.   0.   0.   0. ]
 [ 0.5  0.5  0.5  0.5  0.5]
 [ 1.   1.   1.   1.   1. ]]


28. Flatten a 2D matrix into a 1D array using two different methods and explain the difference.

In [28]:
import numpy as np

mat = np.array([[1, 2], [3, 4]])

# .flatten() always returns a copy (safe)
flat_copy = mat.flatten()

# .ravel() returns a view if possible (memory efficient)
flat_view = mat.ravel()

print(flat_copy)


[1 2 3 4]


29. Calculate the Frobenius Norm of a `3x3` matrix.

In [29]:
import numpy as np

A = np.arange(9).reshape(3, 3)

# ord='fro' specifies the Frobenius norm (sqrt of sum of squares)
norm = np.linalg.norm(A, ord='fro')

print("Frobenius Norm:", norm)


Frobenius Norm: 14.2828568570857


30. Create a script to compare the time taken to sum 1 million numbers using a 
python list vs. a NumPy array.

In [30]:
import numpy as np
import time

size = 1000000
py_list = list(range(size))
np_arr = np.arange(size)

# Time python list
start = time.time()
sum(py_list)
print(f"Python list time: {time.time() - start}")

# Time NumPy array
start = time.time()
np_arr.sum() # Vectorized sum
print(f"NumPy time: {time.time() - start}")


Python list time: 0.03864908218383789
NumPy time: 0.001050710678100586


## Advanced / Best Practices Exercises

31. Use `np.newaxis` to convert a `1D` array into a column vector.


In [31]:
import numpy as np

arr = np.array([1, 2, 3])

# Increases dimension by adding a new axis at the specified position
col_vector = arr[:, np.newaxis]

print("Shape:", col_vector.shape) # (3, 1)
print(col_vector)


Shape: (3, 1)
[[1]
 [2]
 [3]]


32. Use `np.genfromtxt` to load a CSV file (simulated here) while handling missing values.

In [32]:
import numpy as np
import io

# Simulated CSV data with a missing value
csv_data = u"1, 2, 3\n4, , 6"
s = io.StringIO(csv_data)

# filling_values replaces empty spots with a default
data = np.genfromtxt(s, delimiter=",", filling_values=0)

print(data)

[[1. 2. 3.]
 [4. 0. 6.]]


33. Implement a simple "Rolling Average" using `np.convolve`.

In [33]:
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6, 7, 8])
window_size = 3

# Create a uniform weight window
weights = np.ones(window_size) / window_size

# valid mode ensures the window fits completely within the data
rolling_avg = np.convolve(data, weights, mode='valid')

print(rolling_avg)


[2. 3. 4. 5. 6. 7.]


34. Use Structured Arrays to store a table with different data types (`Name, Age, Grade`).

In [34]:
import numpy as np

# Define the structure: 'U10' for string, 'i4' for int, 'f4' for float
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('grade', 'f4')])

# Create array with the defined dtype
students = np.array([('Alice', 21, 88.5), ('Bob', 22, 92.0)], dtype=dt)

print(students['name']) # Access specific field


['Alice' 'Bob']


35. Use `np.clip` to limit the values in an array between a minimum of 10 and a maximum of 50.

In [35]:
import numpy as np

data = np.array([5, 15, 45, 100, 25])

# Values < 10 become 10, values > 50 become 50
clipped = np.clip(data, 10, 50)

print(clipped)


[10 15 45 50 25]


36. Demonstrate Memory Mapping with `np.memmap` for processing files too large for RAM.

In [36]:
import numpy as np

# Create a large file on disk (simulated)
# mode='w+' creates/overwrites file
filename = "large_data.dat"
fp = np.memmap(filename, dtype='float32', mode='w+', shape=(1000, 1000))

# Operations happen on disk, not fully loaded into RAM
fp[:] = np.random.rand(1000, 1000)
fp.flush() # Ensure data is written to disk

print("Data mapped to disk successfully.")


Data mapped to disk successfully.


37. Find the unique elements and their counts in an array.

In [37]:
import numpy as np

data = np.array([1, 2, 2, 3, 3, 3, 4])

# return_counts=True gives the frequency of each item
values, counts = np.unique(data, return_counts=True)

print(dict(zip(values, counts)))


{1: 1, 2: 2, 3: 3, 4: 1}


38. Tile an array to repeat a pattern.

In [38]:
import numpy as np

pattern = np.array([1, 2, 3])

# Repeat the pattern 3 times horizontally
tiled = np.tile(pattern, 3)

print(tiled) # [1, 2, 3, 1, 2, 3, 1, 2, 3]


[1 2 3 1 2 3 1 2 3]


39. Use `np.allclose` to check if two arrays are mathematically equal within a small tolerance.

In [39]:
import numpy as np

a = np.array([0.1 + 0.2])
b = np.array([0.3])

# Floating point precision often makes '==' fail
print("Equality:", a == b) 

# allclose is the best practice for comparing floats
print("Close enough:", np.allclose(a, b))


Equality: [False]
Close enough: True


40. Create a custom ufunc (Universal Function) using `np.frompyfunc`.

In [40]:
import numpy as np

def my_logic(x):
    return x**2 + 10

# Convert standard Python function to a NumPy ufunc
# 1 input, 1 output
vectorized_logic = np.frompyfunc(my_logic, 1, 1)

data = np.array([1, 2, 3])
print(vectorized_logic(data))

[11 14 19]
